- name: Add the Cloudera Repository
  apt-repository: repo="deb {{ repo }}" state=present

- name: Add the Cloudera src Repository
  apt-repository: repo="deb-src {{ repo }}" state=present

- name: Add the Cloudera APT Repository key
  apt-key: data="{{ lookup('file', 'cloudera-repo.key') }}" state=present

- name: Add the Cloudera APT preference
  copy: src=cloudera.pref dest=/etc/apt/preferences.d