- hosts: hadoop_client
  gather_facts: no
  sudo: True
  sudo_user: hdfs
  tasks:
    - name: make_root_dir
      shell: hdfs dfs -mkdir -p /hbase

    - name: chown_root_dir
      shell: hdfs dfs -chown -R hbase:hbase /hbase