- name: copy the hbase configuration files
  template: src=../../roles/cdh5_hbase_master/templates/{{ item }}.j2 dest=/etc/hbase/conf/{{ item }} mode=64
  with_items:
    - hbase-site.xml
- name: set manage zookeeper to false
  sudo: yes
  lineinfile: dest=/etc/hbase/conf/hbase-env.sh regexp='export HBASE_REGIONSERVER_OPTS' line='export HBASE_REGIONSERVER_OPTS="{{ hbase_regionserver_opts }}"'


